name: openapi_petstore
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  http: ^1.2.1
  xml: ^6.5.0
  # json_annotation: ^4.9.0
  shared_infrastructure:
    path: shared_infrastructure
  meta: ^1.15.0
  std_uritemplate: ^1.0.1
  

dev_dependencies:
  # build_runner: ^2.4.11
  # json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
