name: shared_infrastructure
description: Shared infrastructure for OpenApi packages
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3
dependencies:
  http_parser: ^4.1.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
